def error():
    print("Error, exception handled")
    #sleep(1)
